"""Added table models

Revision ID: 5f304a11154f
Revises: fefd0f9d0329
Create Date: 2024-01-08 15:20:14.073837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f304a11154f'
down_revision = 'fefd0f9d0329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
