"""Added table models

Revision ID: fefd0f9d0329
Revises: 1af8f843304f
Create Date: 2024-01-08 14:57:05.771457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefd0f9d0329'
down_revision = '1af8f843304f'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('flight', sa.DateTime(), nullable=True),
    sa.UniqueConstraint('email', name='unique_email')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
